# TODO: Works for development but supposedly breaks Atom/RSS feeds? 
base_url = "/"
compile_sass = true
generate_robots_txt = true
minify_html = true
author = "Biixie"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
error_on_missing_highlight = true
smart_punctuation = true
bottom_footnotes = true
insert_anchor_links = "heading"

[extra]
# Put all your custom variables here
